CREATE TABLE IF NOT EXISTS `assets` (  
  `CLIENT_MAC` VARCHAR(255),
  `CLIENT_VNCPWD` VARCHAR(255),
  `CLIENT_CFGPWD` VARCHAR(255),
  `CLIENT_DFAPP` VARCHAR(255),
  `CLIENT_DFSRV` VARCHAR(255),
  `CLIENT_MEM` VARCHAR(255),
  `CLIENT_GPU` VARCHAR(255),
  `CLIENT_CPU` VARCHAR(255),
  `CLIENT_NIC` VARCHAR(255),
  `CLIENT_OS` VARCHAR(255),
  `CLIENT_Model` VARCHAR(255),
  `CLIENT_STORAGE` VARCHAR(255),
  `CLIENT_KERNEL` VARCHAR(255),
  `CLIENT_IP` VARCHAR(255),
  `CLIENT_AUDIO` VARCHAR(255),
  `CLIENT_VERSION` VARCHAR(255),
  `CLIENT_NAME` VARCHAR(255),
  `CLIENT_FREQ`  VARCHAR(255),
  `CLIENT_DISPLAY` VARCHAR(255),
  `CLIENT_OPT` VARCHAR(255), 
  `CLIENT_SESSION_0_TYPE` VARCHAR(255),
  `CLIENT_LANGUAGE` VARCHAR(255),
  PRIMARY KEY(`CLIENT_MAC`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


